insert into public.medication (id, prescription_id, dosage, name)
values  (1, 1, '2 puffs every 4-6 hours', 'Albuterol'),
        (2, 1, '10 mg daily', 'Loratadine'),
        (3, 2, '10 mg daily', 'Lisinopril'),
        (4, 2, '200 mg as needed', 'Ibuprofen'),
        (5, 3, '5 mg daily', 'Amlodipine'),
        (6, 3, '25 mg twice daily', 'Metoprolol'),
        (7, 4, '500 mg twice daily', 'Metformin'),
        (8, 4, '20 mg daily', 'Atorvastatin'),
        (9, 4, '81 mg daily', 'Aspirin'),
        (10, 5, '20 units daily', 'Insulin Glargine'),
        (11, 5, '10 mg daily', 'Rosuvastatin'),
        (12, 6, '50 mg as needed', 'Sumatriptan'),
        (13, 6, '40 mg twice daily', 'Propranolol'),
        (14, 6, '500 mg as needed', 'Acetaminophen'),
        (15, 7, '25 mg twice daily', 'Topiramate'),
        (16, 7, '400 mg as needed', 'Ibuprofen'),
        (17, 8, '50 mg daily', 'Sertraline'),
        (18, 8, '25 mg as needed', 'Hydroxyzine'),
        (19, 8, '0.5 mg as needed', 'Lorazepam'),
        (20, 9, '1% cream twice daily', 'Hydrocortisone'),
        (21, 9, '10 mg daily', 'Cetirizine'),
        (22, 9, '0.1% ointment daily', 'Triamcinolone'),
        (23, 10, '25 mg daily', 'Hydrochlorothiazide'),
        (24, 10, '50 mg daily', 'Losartan'),
        (25, 10, '81 mg daily', 'Aspirin');