create table roles
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        unique
);

alter table roles
    owner to root;

create table users
(
    enabled  boolean      not null,
    id       bigint generated by default as identity
        primary key,
    email    varchar(255) not null
        unique,
    name     varchar(255) not null,
    password varchar(255) not null
);

alter table users
    owner to root;

create table patient
(
    date_of_birth   date,
    id              bigint generated by default as identity
        primary key,
    user_id         bigint
        unique
        constraint fkie6vajiyur53rjcl5nc2pe83t
            references users,
    medical_history varchar(255)
);

alter table patient
    owner to root;

create table prescription
(
    issued_date date,
    doctor_id   bigint
        constraint fksq7r3ce0tk4nje27vm2tla82m
            references users,
    id          bigint generated by default as identity
        primary key,
    patient_id  bigint
        constraint fkqrlh184tfvdi95erwl65p4xj3
            references patient
);

alter table prescription
    owner to root;

create table medication
(
    id              bigint generated by default as identity
        primary key,
    prescription_id bigint
        constraint fkiwq0ga4lun6iwyqkwyy5nf8et
            references prescription,
    dosage          varchar(255),
    name            varchar(255)
);

alter table medication
    owner to root;

create table user_roles
(
    role_id bigint not null
        constraint fkh8ciramu9cc9q3qcqiv4ue8a6
            references roles,
    user_id bigint not null
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references users
);

alter table user_roles
    owner to root;
