version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_healthcare
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: HealthcareSystem
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - my_network

  postgresql:
    image: 'bitnami/postgresql:latest'
    restart: unless-stopped
    environment:
      POSTGRESQL_DATABASE: HealthcareSystem
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - my_network

  app:
    image: afikur/healthcare
    container_name: healthcare
    environment:
      DB_URL: jdbc:postgresql://postgresql:5432/HealthcareSystem
      DB_USERNAME: root
      DB_PASSWORD: secret
    networks:
      - my_network
    ports:
      - "8080:8080"
    restart: always
volumes:
  data: { }

networks:
  my_network: